// GhostBounty event ABI fragments for ethers.js log parsing
export const GHOST_BOUNTY_EVENTS = [
  "event BountyCreated(uint256 indexed bountyId, string repoOwner, string repoName, uint64 issueNumber, uint256 timestamp)",
  "event BountyCancelled(uint256 indexed bountyId, uint256 timestamp)",
  "event ClaimRequested(uint256 indexed bountyId, bytes32 indexed requestId, uint64 prNumber, uint256 timestamp)",
  "event BountyVerified(uint256 indexed bountyId, address indexed developer, uint256 timestamp)",
  "event BountyPaid(uint256 indexed bountyId, address indexed developer, uint256 timestamp)",
  "event ClaimFailed(uint256 indexed bountyId, bytes32 indexed requestId, string reason)",
  "event DevRegistrationRequested(address indexed dev, string githubUsername, bytes32 indexed requestId)",
  "event DevRegistered(address indexed dev, string githubUsername)",
  "event DevRegistrationFailed(address indexed dev, bytes32 indexed requestId, string reason)",
  "event FeesCollected(address indexed treasury)",
  "event SecretsUpdated(uint8 slotId, uint64 version, uint256 expiration)",
  "event SourceChangeProposed(string sourceType, bytes32 indexed sourceHash, uint256 executeAfter)",
  "event SourceChangeExecuted(string sourceType, uint256 timestamp)",
  "event SourceChangeCancelled(string sourceType)",
  "event FeeChangeProposed(uint256 newFeeBps, uint256 executeAfter)",
  "event FeeChangeExecuted(uint256 newFeeBps)",
  "event TreasuryChangeProposed(address newTreasury, uint256 executeAfter)",
  "event TreasuryChangeExecuted(address newTreasury)",
  "event DonIdUpdated(bytes32 newDonId)",
  "event SubscriptionIdUpdated(uint64 newSubId)",
  "event CallbackGasLimitUpdated(uint32 newLimit)",
] as const;
